### ISSUE TITLE
Cannot Search - What Went Wrong?

### ISSUE THREAD

**Issue by formeo14** [arnesacnussem/jellyfin-plugin-meilisearch#10]
**Description:**

I installed the plugin and connected it to a Meilisearch instance (v1.9, v1.11.2, or v1.12.0). However, the search functionality is not working as expected. The plugin reports that it is operating correctly, but every search query returns "no item found."

**Error Logs:**

I frequently encounter errors like these:
```
2024-12-26T01:31:36.037446Z INFO HTTP request{method=POST host="meilisearch:7700" route=/indexes/XXXXX/search query_parameters= user_agent=Meilisearch .NET (v0.15.3) status_code=400 error=Index `XXXXX`: Attribute `type` is not filterable. This index does not have configured filterable attributes.
1:5 type = MediaBrowser.Controller.Entities.Movies.Movie}: tracing_actix_web::middleware: Error encountered while processing the incoming HTTP request: ResponseError { code: 400, message: "Index `XXXXX`: Attribute `type` is not filterable. This index does not have configured filterable attributes.\n1:5 type = MediaBrowser.Controller.Entities.Movies.Movie", error_code: "invalid_search_filter", error_type: "invalid_request", error_link: "https://docs.meilisearch.com/errors#invalid_search_filter" }

2024-12-26T01:24:21.142694Z INFO HTTP request{method=POST host="meilisearch:7700" route=/indexes/XXXXX/search query_parameters= user_agent=Meilisearch .NET (v0.15.3) status_code=400 error=Index `XXXXX`: Attribute `type` is not filterable. This index does not have configured filterable attributes.
1:5 type = MediaBrowser.Controller.Entities.Movies.Movie}: meilisearch 2024-12-26T01:26:32.500Z m: close time.busy=288µs time.idle=350µs
```

**Troubleshooting Steps Taken:**
- Tried scheduled jobs – no improvement.
- Checked the library configuration – no improvement.

**Plugin Status:**
```
db: /config/data/data/library.db
meilisearch: Server: available
meilisearchOk: true
lastIndex: 12/26/2024 12:17:23 AM +00:00
lastIndexed: 115155
averageSearchTime: 2ms
```

**Additional Information:**
- The search does not work when the fallback to Jellyfin is disabled.
- With fallback to Jellyfin enabled, the search is very slow due to using Jellyfin.

**Request:**
What could be causing these issues, and how can they be resolved?

**Comment by arnesacnussem** [comment]
you can try delete the meilisearch index and recreate(by restart jellyfin) it.
I've seen this problem once, it was caused by configuration lost in the meilisearch index.
tools like https://meilisearch-ui.riccox.com would be handy

**Comment by formeo14** [comment]
Thank you, I ill test it out.

**Comment by formeo14** [comment]
"@arnesacnussem It's working now, thank you! While it isn’t faster than Jellyfin, it delivers better search results. Meilisearch only requires `time.busy=183µs`, but the results appear just as quickly as with Jellyfin—possibly because it displays more results, though I’m not entirely sure. Thanks for this plugin; it’s much easier to set up than Jellysearch!"
