### ISSUE TITLE
Version 1.8 NotSupported by jellyfin 10.10.x

### ISSUE THREAD

**Issue by funkadhafi** [arnesacnussem/jellyfin-plugin-meilisearch#2]
Hi arnesacnussem, 
Tank you for this great plugin. But I just upgraded to your latest version Meilisearch1.8.0.0 and Jellyfin 10.10.1 refused to use it saying NotSupported ? The previous version 1.7 was working very well.

**Comment by arnesacnussem** [comment]
Hi, 
thank you for point it out, it caused by a wrong SQLite assemble version in config file
I've update the plugin to v1.8.1.0 and it should work now.
