### ISSUE TITLE
Scan Media Library stuck

### ISSUE THREAD

**Issue by muisje** [arnesacnussem/jellyfin-plugin-meilisearch#9]
When this plugin is enabled the scan media library task gets stuck at the end (~95%) and never finishes. 

Besides that the plugin works for me, it's super cool, but not being able the library is a pretty significant issue.

**Comment by arnesacnussem** [comment]
I'm glad to help but I need more Information：
status on the plugin configuration page, log from jellyfin, and version of both jellyfin and plugin.

The library scan surely will wait for this plugin to finish update index,  But it should be fairly quick, I mean, for myself, 1 million documents only tooks a few second. Are you not self-host a meilisearch instance?

**Comment by muisje** [comment]
Hmmm the problem doesn't happen after enabling it again since today. Thanks for helping me

Jellyfin server version 10.10.3
Jellyfin meilisearch plugin version 1.10.1.0
Meilisearch version 1.11.3

plugin status:

db: /config/data/library.db
meilisearch: Server: available
meilisearchOk: true
lastIndex: 12/22/2024 5:35:40 PM +00:00
lastIndexed: 7147
averageSearchTime: 7ms

**Comment by arnesacnussem** [comment]
glad to know it is working now :)
updating 7k of documents should finish within one second I thought, which is likely not the reason it stuck at 95%.
um, guess I should add a status for the time consumed of index update.

closing this. If you have any questions, feel free to reopen or create a new one.
